### ISSUE TITLE
Add debugger GUI

### ISSUE THREAD

**Issue by kirillkh** [intellij-rust/intellij-rust.github.io#36] opened 2016-12-05 17:20 UTC
I've been using the plugin for some time now, and it works great! The feature I'm missing the most right now is debugger GUI. Nothing would make my life so much easier than this.

**Comment by mkaput** [comment] 2016-12-05 19:46
Hi!

This is repo for our website, while plugin's repo lies here: https://github.com/intellij-rust/intellij-rust

This issue is a duplicate of intellij-rust/intellij-rust#535, and we certainly plan to implement this 😄

**Closed by mkaput** 2016-12-05 19:46 UTC

**Comment by kirillkh** [comment] 2016-12-05 21:32
Oops, sorry.
